<?php
include 'Model.php';
echo $demo;
?>

  <div class="checkbox">    
    <input type="checkbox" id="check-me">  

    <label for="check-me">
      <span class="check"></span>
      <span class="box"></span>
      <span class="cb-text">Notifications</span>
    </label>  
	</div>

  <div class="checkbox">    
    <input type="checkbox" id="check-me2">  

    <label for="check-me2">
      <span class="check"></span>
      <span class="box"></span>
      <span class="cb-text">Notifications</span>
    </label>  
    
</div>