<link href="/Modules/Login/Public/css/styles.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Login/Public/js/scripts.js"></script>

<div id="boxLogin" style="display:none">

	<div class="content">

		<div class="account-user" style="background-image: url('<?php echo ( $_COOKIE['ActiveUserLogin'] && $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Image'] ? $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Folder'] . '/' . $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Image'] : '/img/icon/account-user.svg' ) ?>')"></div> <br><br>
		<h1 class="nameUser">Olá, Kelvin Souza</h1>

		<div class="bodyLogin">

			<span class="input input--minoru">
				<input type="text" name="email" class="input__field input__field--yoko" id="fldEmail" <?php echo ( !empty( $_COOKIE['ActiveUserLogin'] ) ? ' value="' . $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Email'] . '" readonly="readonly"' : false ); ?>>
				<label class="input__label input__label--yoko" for="fldEmail">
					<span class="input__label-content input__label-content--yoko"><?php echo __('Seu email') ?></span>
				</label>
			</span> <br><br>

			<span class="input input--minoru">
				<input type="password" name="pass" class="input__field input__field--yoko" id="fldPass">
				<label class="input__label input__label--yoko" for="fldPass">
					<span class="input__label-content input__label-content--yoko"><?php echo __('Sua senha') ?> </span>
				</label>
			</span> <br><br>

			<button id="Logar" type="submit" class="button btn btn-primary fR"><i class="material-icons fL">lock_outline</i> <?php echo __('Entrar') ?></button>
			<?php echo ( !empty( $_COOKIE['ActiveUserLogin'] ) ? '<button id="HistoryUsers" class="button btn btn-primary fL"><i class="material-icons">keyboard_arrow_left</i> ' . _('Logar com outro usuário') . '</button>' : false ); ?>
	
		</div>

	</div>

</div>

<?php if( !empty( $_COOKIE['ActiveUserLogin'] ) ){ ?>

<ul id="listHistoryUsers">
	<li data-email="" data-bg="/img/icon/account-user.svg"><div class="bg-user" style="background-image: url('/img/icon/account-user.svg')"></div> <?php echo _('Adicionar conta') ?></li>
	<?php foreach ( $_COOKIE['HistoryUsers'] as $id => $u ){ ?>
	<li data-email="<?=$u['Email']?>" data-bg="<?php echo ( !empty( $u['Image'] ) ? $u['Folder'] . '/' . $u['Image'] : '/img/icon/account-user.svg' ) ?>"><div class="bg-user" style="background-image: url('<?php echo ( !empty( $u['Image'] ) ? $u['Folder'] . '/' . $u['Image'] : '/img/icon/account-user.svg' ) ?>')"></div> <?=$u['Nome']?></li>
	<?php } ?>
</ul>

<?php } ?>

<script type="text/javascript">
	Waves.attach('.button');
	Waves.init();

	(function() {
		// trim polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
		if (!String.prototype.trim) {
			(function() {
				// Make sure we trim BOM and NBSP
				var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
				String.prototype.trim = function() {
					return this.replace(rtrim, '');
				};
			})();
		}

		[].slice.call( document.querySelectorAll( 'input.input__field' ) ).forEach( function( inputEl ) {
			// in case the input is already filled..
			if( inputEl.value.trim() !== '' ) {
				classie.add( inputEl.parentNode, 'input--filled' );
			}

			// events:
			inputEl.addEventListener( 'focus', onInputFocus );
			inputEl.addEventListener( 'blur', onInputBlur );
		} );

		function onInputFocus( ev ) {
			classie.add( ev.target.parentNode, 'input--filled' );
		}

		function onInputBlur( ev ) {
			if( ev.target.value.trim() === '' ) {
				classie.remove( ev.target.parentNode, 'input--filled' );
			}
		}
	})();
</script>