<?php 
if( !$Function->isAjax() ){
	include ROOT . '/' . $Path . 'Head.phtml';
	include ROOT . '/' . $Path . 'Menu.phtml';
	echo '<div class="content">';
} ?>


<div class="w80">

	<h1><span>Entre em contato</span></h1>

	<div class="mdl-cell mdl-cell--6-col fL">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2948.645465759004!2d-71.50696654896582!3d42.350081579085376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e38b8a4520278b%3A0x1f1795f17362ea8b!2s650+Boston+Post+Rd+E%2C+Marlborough%2C+MA+01752%2C+USA!5e0!3m2!1spt-BR!2sbr!4v1455459112865" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>

	<div class="mdl-cell mdl-cell--6-col fR">
		<?php include __DIR__ . '/blocks/contato.php'; ?>
	</div>

</div>

<?php include __DIR__ . '/blocks/ultimas-postagens.php'; ?>

<?php
if( !$Function->isAjax() ){
	echo '</div>';
	include ROOT . '/' . $Path . 'Footer.phtml';
} ?>