<?php 
if( !$Function->isAjax() ){
	include ROOT . '/' . $Path . 'Head.phtml';
	include ROOT . '/' . $Path . 'Menu.phtml';
	echo '<div class="content">';
} 
$Post = $Database->Search('calendar_4', false, "id_calendar=" . $Url[2]);
$Date = explode('-', $Post->date );
?>

<?php if(! $Post ){ ?>

<div class="errorTheme"><i class="material-icons">error_outline</i> OOOOPS!... Essa página não existe!</div>

<?php } else { ?>
<div style="position:relative;z-index:5">

<div class="postContent">

	<div class="card-event mdl-card mdl-shadow--2dp">
	  <div class="mdl-card__title mdl-card--expand">
	    <h4>
	      <?php echo substr( $Function->getMonth( $Date[1] ), 0, 3 ) . ' ' . $Date[2] . ', ' . $Date[0] ?><br>
	      <?=$Post->hour_ini . ' / ' . $Post->hour_end?> <br>
	    
	    <span><?=$Post->endereco?></span>

	    </h4>
	  </div>
	  <div class="mdl-card__actions mdl-card--border">
	    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect openFunction" href="/agenda">
	      <i class="material-icons fL">arrow_back</i>
	    </a>
	    <div class="mdl-layout-spacer"></div>
	    <i class="material-icons">event</i>
	  </div>
	</div>

	<h1><span><?=$Post->title?></span></h1>

	<div class="fb-like mL" data-href="http://<?=implode('.', $Domain) . '/' . implode('/', $Url)?>"></div><br><br>

	<br><br>

	<div class="text">
		<?=$Post->content?>
	</div>

	<?php 

	if( $Post->coment == '1' ){ ?>

	<div class="fb-comments" data-href="http://<?=implode('.', $Domain) . '/' . implode('/', $Url); ?>" data-numposts="15" data-width="100%"></div>

	<?php } ?>

</div>

</div>

<div class="postImage" <?php if( !empty( $Post->image ) ){ ?>style="background-image:url('<?=$Post->image?>')"<?php } ?>></div>

<br><br><br>
<?php } 
if( !$Function->isAjax() ){
	echo '</div>';
	include ROOT . '/' . $Path . 'Footer.phtml';
} ?>