<div class="mdl-spinner mdl-js-spinner is-active"></div>

<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <!--ul class="mdl-mini-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul-->

    <ul class="mdl-mini-footer__link-list">
    	<li><span>© Copyright <?=date('Y')?> - IRPC, todos os direitos reservados. </span></li>
    	<li>650 Boston Post Road East, Marlboro Ma 01752</li>
    	<li>Cultos: Segunda-Feira ás 7pm Culto de Oração, 
          Quarta-Feira ás 8pm Noite da Benção, 
          Domingo ás 10am Escola Bíblica Dominical e 
          Domingo 7pm Culto de Adoração e Louvor</li>
    	<!--li><a href="/contato" class="openFunction" title="Contato | <?=Title?>">contato@ipri.org.br</a></li-->
    </ul>
  </div>
</footer>


</body>
</html>