<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">

	<title><?php echo Title; ?></title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-pink.min.css">
	<link href="<?=$Path?>css/styles.css" rel="stylesheet">
	<link href="<?=$Path?>css/lightbox.css" rel="stylesheet">
	<link href="<?=$Path?>css/nivo-slider.css" rel="stylesheet">

	<script type="text/javascript" src="/Public/js/jquery.min.js"></script>
	<script type="text/javascript" src="<?=$Path?>js/scripts.js"></script>
	<script type="text/javascript" src="<?=$Path?>js/lightbox.min.js"></script>
	<script type="text/javascript" src="<?=$Path?>js/jquery.nivo.slider.pack.js"></script>
	
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
	<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">

</head>
<body>