<?php 
if( !$Function->isAjax() ){
	include ROOT . '/' . $Path . 'Head.phtml';
	include ROOT . '/' . $Path . 'Menu.phtml';
	echo '<div class="content">';
}
?>

	<?php
	/* Slide */
	$Result = $Database->Fetch( 'blog_4', false, "publish='1'", 'id_blog DESC, visitas DESC', false, 4 );
	$Loop	= 1;
	
	echo '<ul class="slide">';
	while( $Slide = $Result->fetch(PDO::FETCH_OBJ) ){
		echo '<li style="background-image: url(\'' . $Slide->image . '\');" class="slide-' . $Loop . ' openFunction" href="/post/' . $Slide->id_blog . '-' . strtolower( $Function->RemoveAccents(  str_replace( ' ', '-', $Slide->title) ) ) . '" title="' . addslashes( $Slide->title ) . ' | ' . Title . '">';

			echo '<span class="title">' . $Slide->title . '</title>';

		echo '</li>';
		$Loop++;
	}
	echo '</ul>';
	/* Ends Slide */
	?>
	


<!-- Image card -->
<style>

</style>

	<?php 

	include __DIR__ . '/blocks/versiculos.php';
	include __DIR__ . '/blocks/ultimas-postagens.php'; ?>

	<br><br>

	<div class="mdl-grid w80 qs">

		<h2><a href="#">Quem Somos</a></h2>

		<div>
			<h3>Nossa História</h3>

			A Igreja Presbiteriana Renovada Internacional de Marlboro USA, fundada pelo Pastor Delcy Dalla Costa e família. Iniciou suas atividades em Outubro de 2001 e completou 13 anos de história Na cidade de  Marlboro, Ma. É caracterizada como uma igreja Pentecostal, dinâmica, bíblica, adoradora, acolhedora e contextualizada. <br>

			Desde então a igreja vem experimentando um extraordinário crescimento espiritual e numérico. <br><br>

			Desde sua fundação, tem caminhado com fé, dando passos ousados que demonstram sua confiança no amor e na grandeza de Deus!<br><br>

			A Igreja Presbiteriana Renovada Internacional tem uma estrutura de ministérios que envolve todas as faixas etárias: departamentos Infantil, de Jovens, de Senhoras, de Varões, Ministério de Missões, Ministério de Intercessão, Ministério de Louvor.
			Para crescimento na palavra e fortalecimento da família cristã, a igreja desenvolve: Escola Bíblica Dominical, Escola Teológica, Encontro de Casais, Seminários e Campanhas.
			Com um trabalho sério, temos colhido os frutos, pessoas têm sido transformadas em verdadeiros adoradores. Somos parte do corpo de Cristo espalahado por esta Terra. Estamos decididos a cumprir a nossa parte na missão de alcançar o mundo para o Senhor Jesus!
			Sempre que desejar, participe de nossas programações e, se precisar, conte conosco. Temos sempre uma equipe pastoral a sua disposição.<br><br>

			Contamos tambem com campo Missionário no Brasil em São Manuel (Pastor Lindomar França Moreira) e Macatuba (Pastor Israel)<br><br>

			Pr. Delcy Dalla Costa & Esposa Pra.Roseli Dalla Costa têm sido instrumentos de Deus para  este tempo de conquistas, juntamente com uma equipe ministerial composta de Evangelistas, Missionárias, presbíteros e um corpo Diaconal.<br><br>

			A Deus, Toda Honra, Toda Glória, Todo Louvor!
		</div>

	</div>

	<?php include __DIR__ . '/blocks/parceiros.php'; ?>

	<br><br><br>


<?php 
if( !$Function->isAjax() ){
	echo '</div>';
	include ROOT . '/' . $Path . 'Footer.phtml';
} ?>