<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <div class="android-header mdl-layout__header mdl-layout__header--waterfall">
    <div class="mdl-layout__header-row">
      <span class="android-title mdl-layout-title">
        <img class="android-logo-image openFunction" href="/home" title="<?=Title?>" src="<?=$Path?>/img/logo.png">
      </span>
      <!-- Add spacer, to align navigation to the right in desktop -->
      <div class="android-header-spacer mdl-layout-spacer"></div>
      <div class="android-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width">
        <!--label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
          <i class="material-icons">search</i>
        </label-->
        <!--div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" id="search-field" />
        </div-->
      </div>
      <!-- Navigation -->
      <div class="android-navigation-container">
        <nav class="android-navigation mdl-navigation">
          <?php
          $Result = $Database->Fetch( 'assuntos', false, false, 'name ASC' );

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( empty( $Url[1] ) || $Url[1] == 'home' ? ' active' : '' ) . '" href="/home" title="' . Title . '"><i class="material-icons fL">&#xE88A;</i></a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'agenda' ? ' active' : '' ) . '" href="/agenda" title="Agenda | ' . Title . '">Agenda</a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'page' || $Url[1] == 'post' ? ' active' : '' ) . '" href="/page" title="Postagens | ' . Title . '">Postagens</a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'galeria-de-fotos' ? ' active' : '' ) . '" href="/galeria-de-fotos" title="Galeria | ' . Title . '">Galeria</a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'pedido-de-oracao' ? ' active' : '' ) . '" href="/pedido-de-oracao" title="Pedido de Oração | ' . Title . '">Pedido de Oração</a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'testemunho' ? ' active' : '' ) . '" href="/testemunho" title="Testemunho | ' . Title . '">Testemunho</a>';

          echo '<a class="mdl-navigation__link mdl-typography--text-uppercase openFunction' . ( $Url[1] == 'contato' ? ' active' : '' ) . '" href="/contato" title="Contato | ' . Title . '">Contato</a>';

          ?>
        </nav>
      </div>
      <!--button class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
        <i class="material-icons">more_vert</i-->
      </button>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
        <li class="mdl-menu__item">5.0 Lollipop</li>
        <li class="mdl-menu__item">4.4 KitKat</li>
        <li disabled class="mdl-menu__item">4.3 Jelly Bean</li>
        <li class="mdl-menu__item">Android History</li>
      </ul>
      <span class="android-mobile-title mdl-layout-title">
        <img class="android-logo-image" src="images/android-logo.png">
      </span>
    </div>
  </div>
</div>