<?php 
if( !$Function->isAjax() ){
	include ROOT . '/' . $Path . 'Head.phtml';
	include ROOT . '/' . $Path . 'Menu.phtml';
	echo '<div class="content">';
}

include __DIR__ . '/blocks/menu-album.php'; ?>


<div class="w80">

	<h1><span>Galeria de Videos</span></h1>

<?php
$Result = $Database->Fetch( 'videos_4' );
while( $Album = $Result->fetch(PDO::FETCH_OBJ) ){ 

?>

<div class="card-image video mdl-card mdl-shadow--2dp openFunction" style="background-image:url('<?=$Album->img?>" href="<?=$Album->url?>" data-title="<?=$Album->title?>" data-description="<?=$Album->descricao?>">
<i class="material-icons">play_circle_outline</i>
  <div class="mdl-card__title mdl-card--expand"></div>
  <div class="mdl-card__actions">
    <span class="card-image__filename"><?=$Album->title?></span>
  </div>
</div>

<?php } ?>

</div>

<div class="modal-video">
	<i class="material-icons close-video">close</i>
	<div class="iframe-video"></div> <br>
	<span class="title-video"></span>
	<p class="description-video"></p>
</div>



<script type="text/javascript">
$('.card-image.video').click(function(){

	var url = $(this).attr('href');
		url = url.split('?v=');

	$('.iframe-video').html('<iframe id="ytplayer" type="text/html" width="100%" height="390"' +
  								'src="http://www.youtube.com/embed/' + url[1] + '?autoplay=1"' +
  								'frameborder="0"/>');

	$('.title-video').html( $(this).attr('data-title') );

	$('.description-video').html( $(this).attr('data-description') );

	$('.modal-video').show();

	return false;
});

$('.modal-video .close-video').click(function(){
	$('.modal-video').hide();
});
</script>

<?php
if( !$Function->isAjax() ){
	echo '</div>';
	include ROOT . '/' . $Path . 'Footer.phtml';
} ?>