<script type="text/javascript" src="/Modules/Stupid_Ball/Public/js/scripts.js"></script>

Pontuacao: <span class="placar">0</span> <br>
Tempo restante: <span id="sessao"></span> <br>
Record: <span class="record">0</span> <br><br>

<div class="teste"></div>

<style type="text/css">
	table tr td{
		border-radius: 50%;
		border: 1px solid;
		background-color: #f44336;
		border: solid 1px #b71c1c;
		margin: 1px;
		font-size: 0;
		width: 15px;
		height: 15px;
		display: inline-block;
		cursor: pointer;
	}
	table tr td:hover{
		background: #efefef;
	}
	.ae {
		background-color: #ef5350;
	}
	.placar {
		font-size: 30px;
		font-family: Tahoma;
		color: #c62828;
	}

</style>