<link href="/Modules/Stupid_Ball/Public/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Stupid_Ball/Public/js/scripts.js"></script>

<span class="txtLabels">Pontuacao:</span> <span class="placar">0</span> <br>
<span class="txtLabels">Tempo restante:</span> <span id="sessao"></span> <br>
<span class="txtLabels">Record:</span> <span class="record">0</span> <br><br>

<div class="teste"></div>
