<link href="/Modules/Explorer/Public/css/styles.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Explorer/Public/js/scripts.js"></script>

<div id="explorerContent">

<?php

$LUrl = '';

foreach ( $Url as $k => $v ){
	if( $k > 0 && !empty( $v ) ){
		$LUrl .= $v . '/';
	}
}

$HTML = '';
$Services->Run('Explorer');

$HTML .= '<ul id="eIcons" data-location="' . $LUrl . '" data-filtro="navPrev=' . $_GET['navPrev'] . '&type=' . $_GET['type'] . '">';

if( ( isset( $_GET['navPrev'] ) && $_GET['navPrev'] == 'true' ) && count( array_filter( $Url ) ) > 1 ){
	$HTML .= '
	<li id="navPrev">
		<i class="material-icons">&#xE166;</i>
		<span>Voltar</span>
	</li>';
}

$HTML .= '
	<li id="uploadifive">
		<button id="upload"></button>
		<span>Upload</span>
	</li>';

foreach( $Explorer->Start() as $Name => $Values ){

	$HTML .= '<li data-info=\'' . json_encode( $Values ) . '\' ' . ( isset( $_GET['Location'] ) && $_GET['Location'] == $Values['Location'] ? ' class="rCliked"' : "" ) . '>';

	if( $Values['Type'] == 'IMAGE' ){
		$HTML .= 
				'<div class="eIcon" style="background-image:url(\'' . $Values['Location'] . '\');"></div>
					<span>' . $Name . '</span>';
	}

	else if( $Values['Type'] == 'FOLDER' ){

		$HTML .= '<i class="material-icons eIcon">&#xE2C7;</i>
					<span>' . $Name . '</span>';

	} else {
		$HTML .= '<i class="material-icons eIcon">&#xE63B;</i>
						<span>' . $Name . '</span>';
	}

	$HTML .= '</li>';
}

$HTML .= '</ul>';


echo $HTML;
?>

</div>

<script type="text/javascript">

if( <?=count( array_filter( $Url ) );?> > 1 && $('#ModuleExplorer .header i#navPrev').length < 1 ){
	$('#ModuleExplorer .header').prepend('<i class="material-icons fL" id="navPrev">&#xE317;</i>');
} else if( <?=count( array_filter( $Url ) );?> == 1 && $('#ModuleExplorer .header i#navPrev').length > 0 ){
	$('#ModuleExplorer .header i#navPrev').remove();
}

/* Uploadfive */

var toJSON = '';

<?php $timestamp = time(); ?>
$('#upload').uploadifive({
	'formData' : {
		'timestamp'   	: '<?php echo $timestamp;?>',
		'token'    		: '<?php echo md5('unique_salt' . $timestamp);?>',
		'Location'		: $('#eIcons').data('location'),
	},

	'progressData'  : 'speed',
	'buttonText'	: '<i class="material-icons">&#xE2C3;</i>',
	'buttonClass'	: 'mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored',
	'queueID'		: 'eIcons',
	'itemTemplate'	: '<li class="uploadifive-queue-item"> <i class="material-icons">&#xE2C2;</i> <div id="p1" class="mdl-progress mdl-js-progress"></div> <span class="filename"></span> </li>',
	'width'			: 62,
	'height'		: 62,
	'auto'        	: true,
	'removeCompleted' 	: false,
	'uploadScript' 	: '/Upload',

	'onProgress'   : function(file, e) {
		file.queueItem.find('.progressbar').width( Math.round( ( e.loaded / e.total ) * 100 ) + '%' );
	},

	'onUploadComplete' : function(file, data) {

		toJSON = JSON.parse( data );

		if( toJSON.Status == true ){

			file.queueItem.find('.progressbar').parent().fadeOut(200);
			setTimeout( function(){
				file.queueItem.find('.progressbar').parent().remove();
			}, 300 );

			file.queueItem.attr('data-info', data).find('i').remove();
			file.queueItem.prepend( ( toJSON.Type == 'IMAGE' ? toJSON.Icon.replace( '{Location}', "'" + toJSON.Location + "'" ) : toJSON.Icon ) ).find('span').text( toJSON.Name );

		} else {
			alert('Erro ao fazer upload!');
		}

	}
});
/* Ends uploadfive */
</script>