<button id="start" class="button"></button>
<div class="lancador">
  <ul></ul>
</div>


<nav id="openStart">

<div class="buscarApps">
	<!-- Expandable Textfield -->
<form action="#">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable textfield-demo">
    <label class="mdl-button mdl-js-button mdl-button--icon" for="searchApps">
      <i class="material-icons" >search</i>
    </label>
    <div class="mdl-textfield__expandable-holder">
      <input class="mdl-textfield__input" type="text" id="searchApps" />
      <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
    </div>
  </div>
</form>
</div> 


  <div class="infoUsersBlock">
    <div class="infoUserLeft">
      <div class="account-user" style="background-image: url('<?php echo ( $_COOKIE['ActiveUserLogin'] && $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Image'] ? $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Folder'] . '/' . $_COOKIE['HistoryUsers'][ $_COOKIE['ActiveUserLogin'] ]['Image'] : '/img/icon/account-user.svg' ) ?>')"></div>

      <div class="infoUser"><b><?php echo $_SESSION['user']['Nome'] . '</b><br>' . $_SESSION['user']['Email'] ?></b></div>
    </div>

    <ul class="nav">
      
      <li class="active" id="apps"><i class="material-icons">apps</i></li>
      <div class="mdl-tooltip" for="apps">
        Aplicativos
      </div>
      
      <li id="work"><i class="material-icons">group_work</i></li>
      <div class="mdl-tooltip" for="work">
        Grupo de Trabalho
      </div>

      <li id="logout"><i class="material-icons">power_settings_new</i></li>
      <div class="mdl-tooltip" for="logout">
        Sair
      </div>

    </ul>

  </div>

	<div for="apps" class="tab" style="display:block">
    <ul class="listModules demo-grid-ruler mdl-grid"></ul>
  </div>

  <div for="work" class="work tab">
    <ul>
      <li>Grupo Padrão</li>
    </ul>
  </div>

  
</nav>

<script type="text/javascript">
  
$("#searchApps").keyup(function(e){
  
  var query = RemoveAccents( $(this).val() );

  if( query == '' ){
    $(".listModules li").show();
  } else {
    $(".listModules li").hide();
    $('.listModules li[data-quest*="' + query.toLowerCase() + '"]').show();
  }

  // if( e.keyCode == 13 ){
    
  // }

});

$('.infoUsersBlock .nav li').click(function(){
  $('.infoUsersBlock .nav li.active').removeClass('active');
  $(this).addClass('active');

  $('nav .tab').hide();
  $('nav .tab[for="' + $(this).attr('id') + '"]').show();
});

</script>