<?php 
sleep(1); 
include 'Model.php';
?>
<link href="/Modules/Desktop/Public/css/styles.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Desktop/Public/js/scripts.js"></script>

<div id="desktop" style="display:none">
	
	<?php 
	include 'Public/Blocks/Menu-Top.phtml';
	include 'Public/Blocks/Menu-Bottom.phtml';
	?>

	<div class="mainDesk btnRigthOn">
		
		<div id="Modules"></div>

	</div>
	
	<div id="menu-desk-bottom"></div>

</div>