<?php 
sleep(1); 
include 'Model.php';
?>
<link href="/Modules/Desktop/Public/css/styles.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Desktop/Public/js/scripts.js"></script>

<div id="desktop" style="display:none">
	
	<?php 
	include 'Public/Blocks/Menu-Top.phtml';
	include 'Public/Blocks/Menu-Bottom.phtml';
	?>
	<div class="mainDesk"></div>
	
	<div id="menu-desk-bottom"></div>

	<button id="upload"></button>

</div>

<script type="text/javascript">
	<?php if( 		isset( $_SESSION['OpenModule'] ) 
				&&	$_SESSION['OpenModule'][1] != '/'
				&&  $_SESSION['OpenModule'][1] != ''
				&&  $_SESSION['OpenModule'][1] != 'Login' 
			){ ?>
		openModule( '<?php echo $_SESSION['OpenModule'][1] ?>' );
	<?php } unset( $_SESSION['OpenModule'] ); ?>

	/* Uploadfive */
	<?php $timestamp = time(); ?>
	$('#upload').uploadifive({
		'formData' : {
			'timestamp'   	: '<?php echo $timestamp;?>',
			'token'    		: '<?php echo md5('unique_salt' . $timestamp);?>',
		}
	});
	/* Ends uploadfive */
</script>