<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <!--ul class="mdl-mini-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul-->

    <ul class="mdl-mini-footer__link-list fR">
    	<li class="fL"><span>© Copyright <?=date('Y')?> - IPRI, todos os direitos reservados. </span></li>
    </ul>
  </div>
</footer>


</body>
</html>