<div class="mdl-spinner mdl-js-spinner is-active"></div>

<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <!--ul class="mdl-mini-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul-->

    <ul class="mdl-mini-footer__link-list">
    	<li><span>© Copyright <?=date('Y')?> - IPRI, todos os direitos reservados. </span></li>
    	<li>Avenida José Horácio Mellão, 2460 (Entrada das Cohabs 1 e 2) - São Manuel-SP</li>
    	<li>Cultos: Quarta-Feira ás 20 hrs, Sexta-Feira ás 20 hrs e Domingo ás 19 hrs</li>
    	<!--li><a href="/contato" class="openFunction" title="Contato | <?=Title?>">contato@ipri.org.br</a></li-->
    </ul>
  </div>
</footer>


</body>
</html>