<?php 
if( !$Function->isAjax() ){
	include ROOT . '/' . $Path . 'Head.phtml';
	include ROOT . '/' . $Path . 'Menu.phtml';
	echo '<div class="content">';
}
?>

	<?php
	/* Slide */
	$Result = $Database->Fetch( 'blog', false, "publish='1'", 'id_blog DESC, visitas DESC', false, 4 );
	$Loop	= 1;
	
	echo '<ul class="slide">';
	while( $Slide = $Result->fetch(PDO::FETCH_OBJ) ){
		echo '<li style="background-image: url(\'' . $Slide->image . '\');" class="slide-' . $Loop . ' openFunction" href="/post/' . $Slide->id_blog . '-' . strtolower( $Function->RemoveAccents(  str_replace( ' ', '-', $Slide->title) ) ) . '">';

			echo '<span class="title">' . $Slide->title . '</title>';

		echo '</li>';
		$Loop++;
	}
	echo '</ul>';
	/* Ends Slide */
	?>
	


<!-- Image card -->
<style>

</style>

	<?php include __DIR__ . '/blocks/ultimas-postagens.php'; ?>

	<br><br>

	<div class="mdl-grid w80 qs">

		<h2><a href="#">Quem Somos</a></h2>

		<div class="mdl-cell mdl-cell--4-col fR">
		<h3>São Manuel</h3>
			A IPRI na cidade de São Manuel, se iniciou em 2005, também em São Manuel foi a primeira cidade a receber a nossa igreja no Brasil. <br>
			Começando com cultos nos lares e hoje estamos em um templo localizado na Avenida José Horácio Mellão, 2460
		</div>

		<div class="mdl-cell mdl-cell--4-col fR">
		<h3>Macatuba</h3>
			A IPRI na cidade de São Manuel, se iniciou em 2005, também em São Manuel foi a primeira cidade a receber a nossa igreja no Brasil. <br>
			Começando com cultos nos lares e hoje estamos em um templo localizado na Avenida José Horácio Mellão, 2460
		</div>

		<div class="mdl-cell mdl-cell--4-col fR">
		<h3>Estados Unidos</h3>
		Este Ministério nasceu a 14 anos na cidade de Malbouroug, no estado de Massachusets, Estados Unidos da América. <br>
		O Senhor usou o pastor Delcy Dalla Costa e sua família, que estão morando na América a 17 anos para iniciarem este Ministério.
		</div>

		<!--p>
		Este Ministério nasceu a 14 anos na cidade de Malbouroug, no   estado de Massachusets, Estados Unidos da América. </p>

		<p>O Senhor usou o pastor Delcy Dalla Costa e sua família, que estão morando na América a 17 anos para iniciarem este Ministério.</p>

        <p>A IPRI chegou ao Brasil no ano de 2005, primeiramente na cidade de São Manuel.</p>

        <p>Atualmente tem Igrejas da IPRI, nas cidades de: São Manuel e Macatuba, podendo expandir nosso Ministério para muitas cidades do nosso estado e nosso país.</p>

        <p>Cremos em Deus como Senhor de tudo, em Jesus Cristo como Salvador, na Bíblia que é a Palavra de Deus, como base para tudo, na ação do Espírito Santo consolador.</p-->

	</div>

	<br><br><br>


<?php 
if( !$Function->isAjax() ){
	echo '</div>';
	include ROOT . '/' . $Path . 'Footer.phtml';
} ?>