<?php 

include ROOT . '/' . $Path . 'Head.phtml';
include ROOT . '/' . $Path . 'Menu.phtml';

?>

<div class="content">
	
	<h2>
		<a href="#">Ultimas postagens</a>
	</h2>

	<div class="mdl-grid w80">
	  <div class="mdl-cell mdl-cell--1-col">1</div>
	  <div class="mdl-cell mdl-cell--1-col">1</div>
	  <div class="mdl-cell mdl-cell--1-col">1</div>
	  <div class="mdl-cell mdl-cell--1-col">1</div>
	</div>

</div>


<?php include ROOT . '/' . $Path . 'Footer.phtml'; ?>