<?php 

if( !$Function->isAjax() ){
  include ROOT . '/' . $Path . 'Head.phtml';
  include ROOT . '/' . $Path . 'Menu.phtml';
  echo '<div class="content">';
}

$idPost = explode( '-', $Url[2] );
$idPost = $idPost[0];

$Post = $Database->Search( 'blog', false, "id_blog='" . $idPost . "'" );
?>

<div class="postImage" style="background-image:url('<?=$Post->image?>')"></div>
<div class="postContent">
	<h1><span><?=$Post->title?></span></h1>

	<div class="fb-like mL" data-href="http://<?=implode('.', $Domain) . '/' . implode('/', $Url)?>"></div><br><br>

	<div class="text">
		<?=$Post->conteudo?>		
	</div>

	<?php if( $Post->coment == '1' ){ ?>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4&appId=832889430108937";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<div class="fb-comments" data-href="http://<?=implode('.', $Domain) . '/' . implode('/', $Url); ?>" data-numposts="15" data-width="100%"></div>

	<?php } ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4&appId=832889430108937";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</div>

<?php 
if( !$Function->isAjax() ){
  echo '</div>';
  include ROOT . '/' . $Path . 'Footer.phtml';
} ?>