<!DOCTYPE html>
<html>
<head>
	<title><?php echo ( !empty( $Conf['ModelInfo']['Title'] ) ? $Conf['ModelInfo']['Title'] . ' | ' . Title : Title ); ?></title>
	<link href="/Public/css/styles.css" rel="stylesheet">
	<script type="text/javascript" src="/Public/js/jquery.min.js"></script>
	<script type="text/javascript" src="/Public/js/waves.min.js"></script>
	<script type="text/javascript" src="/Public/js/classie.js"></script>
</head>
<body>