<!DOCTYPE html>
<html>
<head>
	<title><?php echo ( !empty( $Conf['ModelInfo']['Title'] ) ? $Conf['ModelInfo']['Title'] . ' | ' . Title : Title ); ?></title>
	<link href="/Public/css/styles.css" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-pink.min.css">
	<script type="text/javascript" src="/Public/js/jquery.min.js"></script>
	<script type="text/javascript" src="/Public/js/angular.min.js"></script>
	<script type="text/javascript" src="/Public/js/DefaultScripts.js"></script>
	<script type="text/javascript" src="/Public/js/waves.min.js"></script>
	<script type="text/javascript" src="/Public/js/classie.js"></script>
	<script type="text/javascript" src="/Public/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/Public/js/rClick.js"></script>
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
	<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
</head>
<body>