<div class="pMenuRigth" data-pjc="<?php echo $j['Config']['nome_projeto']; ?>">
	
	<ul class="op">

		<li data-content="p-pages" class="active">

			<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" id="opPages">
	  			<div class="material-icons">&#xE24D;</div>
			</button>
			<div class="mdl-tooltip" for="opPages">Páginas</div>

		</li>

		<li data-content="p-blocks">

			<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" id="opMenu">
	  			<i class="material-icons">&#xE8F0;</i>
			</button>
			<div class="mdl-tooltip" for="opMenu">Blocos</div>

		</li>

	</ul>

	<div class="select">

		<ul id="p-pages">
			
			<li class="new">
				<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" style="width:100%">
					<i class="material-icons fL">add</i>
					Criar Página
				</button>
			</li>


			<?php 
			$loop = 0;
			foreach ( $j['Pages'] as $k => $v ){ ?>
				<li data-info='<?php echo json_encode( $v ) ?>' <?php echo ( $loop === 0 ? 'class="active"' : "" ); ?> id="<?=$k?>" data-title="<?=$v['Title']?>">
					<div class="view">
						<i class="material-icons fL">&#xE5CC;</i> <?=$v['Title']?> 
						<?php if( $j['Config']['Index'] === $k ){ ?>
						<i class="material-icons" id="s-home">&#xE88A;</i>
							<div class="mdl-tooltip" for="s-home">Página inicial</div>
						<?php } ?>						
					</div>

					<div class="edit" style="display:none;">
						<input value="<?=$v['Title']?>">
					</div>

				</li>
			<?php $loop++; } ?>

		</ul>

		<ul id="p-blocks">
			<li class="pBlock" data-layout="1">
				<div style="width:90%">
					100%
				</div>
			</li>

			<li class="pBlock" data-layout="2">
				<div style="width:40%">
					50%
				</div>

				<div style="width:40%">
					50%
				</div>
			</li>

			<li class="pBlock" data-layout="3">
				<div style="width:23%">
					33%
				</div>

				<div style="width:23%">
					33%
				</div>

				<div style="width:23%">
					33%
				</div>
			</li>

			<li class="pBlock" data-layout="4">
				<div style="width:15%">
					25%
				</div>

				<div style="width:15%">
					25%
				</div>

				<div style="width:15%">
					25%
				</div>

				<div style="width:15%">
					25%
				</div>
			</li>

			<li class="pBlock" data-layout="5">
				<div style="width:60%">
					70%
				</div>

				<div style="width:20%">
					30%
				</div>
			</li>

			<li class="pBlock" data-layout="6">
				<div style="width:20%">
					30%
				</div>

				<div style="width:60%">
					70%
				</div>
			</li>

		</ul>
		
	</div>


</div>

<script type="text/javascript">

$(document).ready(function(){

	$('.op li button').click(function(){

		$('.select ul').hide();
		$('.op li').removeClass('active');
		$(this).parent('li').addClass('active');

		$('.select ul#' + $(this).parent('li').data('content') ).show();
	});

	$('.pMenuRigth #p-pages').sortable({
		items: "li:not(.new)",
		stop: function( event, ui ) {
			
			var Sequence = '',
				Loop     = 1;

			$('.pMenuRigth #p-pages li').each(function(){
				if( $(this).attr('id') != undefined ){
					Sequence += $(this).attr('id') + ':' + Loop + ';';
					Loop++;
				}
			});

			$.ajax({ 
		    	type: "POST",
		    	dataType: "json",
		    	cache: false,
		    	data: {
		    		Pjc : '<?php echo $j['Config']['nome_projeto']; ?>',
		    		Sequence: Sequence
		    	},
		    	url: '/Projects/Ajax/SaveSequence', 
		    	success: function(Data){ 
		    		$.each( Data, function(k, v){
		    			$('#' + k.replace('.', '\\.') ).attr('id', v);
		    		});
		    	}
		    });

		}
	});	

	$('.op li button:first').click();

	function rename( This ){
		This.find('.edit').show();
		This.find('.view').hide();
	}

	$('#p-blocks li').draggable({ 
		opacity: 0.7, 
		helper: 'clone',
		appendTo: '#ModuleProjects',
		cursorAt: {
			left: 5,
			top : 5
		}
	});

    $("#stage").droppable({
      drop: function( event, ui ) {
        $(this).removeClass( "drop" );
		$.ajax({ 
	    	type: "POST",
	    	dataType: "json",
	    	cache: false,
	    	data: {
	    		Page: $('#p-pages li.active').attr('id'),
	    		Pjc : '<?php echo $j['Config']['nome_projeto']; ?>',
	    		Layout: ui.draggable.data('layout')
	    	},
	    	url: '/Projects/Ajax/CreateGrid', 
	    	success: function(Grid){ 
	    		if( Grid.Status === true ){
	    			LoadPage( $('#p-pages li.active').attr('id') );
	    		}
	    	}
	    });
      },

      over: function( event, ui ){
      	$(this).addClass( "drop" );
      },

      out: function( event, ui ){
      	$(this).removeClass( "drop" );
      }
    });

	$('#p-pages li:not(".new")').rClick({

		id: 's-page-rClick',

		Menu: {

			rename: {

				icon: '<i class="material-icons">&#xE150;</i>',
				text: 'Renomear',
				exec: function(This){
					rename( This );
				}

			},

			delete: {
				icon: '<i class="material-icons">&#xE872;</i>',
				text: 'Excluir página',
				exec: function(This){
					
					var isDelete 	= confirm("Tem certeza que deseja deletar esta página?");

					if( isDelete == true ){
						$.ajax({ 
					    	type: "POST",
					    	dataType: "json",
					    	cache: false,
					    	data: {
					    		Page: This.attr('id'),
					    		Pjc : '<?php echo $j['Config']['nome_projeto']; ?>'
					    	},
					    	url: '/Projects/Ajax/DeletePage', 
					    	success: function(Page){ 
					    		if( Page.Status === true ){
					    			This.remove();
					    		}
					    	}
					    });
					}
				}
			},
		}
	});

	$('#p-pages li.new').click(function(){

		var NewPage 	= 'Nova Página',
			LoopName	= true,
			Loop 		= 0;

		while( LoopName ){
			if( $('#p-pages li[data-title="' + NewPage + ( Loop === 0 ? '' : '-' + Loop ) + '"]').length > 0 ){
				Loop++;
			} else {
				NewPage 	= NewPage + ( Loop === 0 ? '' : '-' + Loop );
				LoopName 	= false;
			}
		}

		$.ajax({ 
	    	type: "POST",
	    	dataType: "json",
	    	cache: false,
	    	data: {
	    		Page: NewPage,
	    		Pjc : '<?php echo $j['Config']['nome_projeto']; ?>'
	    	},
	    	url: '/Projects/Ajax/CreatePage', 
	    	success: function(Page){ 

	    		if( Page.Status == true ){

	    			$('.select li').removeClass('active');

					$('.select li.new').after('<li data-info=\'' + JSON.stringify( Page ) + '\' class="active" id="' + Page.File + '" data-title="' + Page.Title + '">' +
						'<div class="view" style="display:none">' +
							'<i class="material-icons fL">&#xE5CC;</i> ' + Page.Title +
						'</div>' +
						'<div class="edit">' +
							'<input value="' + Page.Title + '">' +
						'</div>' +
					'</li>');

					$('.select input:first').focus();
	    		}
			}
	    });

	});

});
</script>