<?php

include 'Model.php';
echo $ModuleCalendar;

?>

<script type="text/javascript">
	var Element = $('#modal[target="CreateCalendar"] [for="CreateCalendar"]');

	if( Element.attr('href').indexOf('?date=') < 0 ){
		Element.attr( 'href', Element.attr('href') + '?date=<?=$_GET['date']?>' );
	}

	$(document).ready(function(){
		$('#flddate').val('<?=$_GET['date']?>').hide();
		$('[for="flddate"]').hide();
	});

	$('i.close').click(function(){
		Change();
	});
</script>