<?php include 'Model.php'; ?>

<?php
$Services->Run('autoSystem');
echo $autoSystem->create( $Usuarios );
?>

<link href="/Modules/Usuarios/Public/css/styles.css" rel="stylesheet">
<script type="text/javascript" src="/Modules/Usuarios/Public/js/scripts.js"></script>

<?php // $Create = $Database->Search('work_groups', 'user_create', "id_work_group = " . $_SESSION['user']['Path']); ?>

<script type="text/javascript">
	// $('tr[for="Usuarios"][data-id="<?=$Create->user_create?>"] .mdl-js-button').remove();
</script>