<?php
$Router['sluup'] = array(
	''				=>	'Modules/Desktop/View',
	'Desktop'		=>	'Modules/Desktop/View',
	'Login'			=>	'Modules/Login/View',
	'Demo'			=>	'Modules/Demo/View',
	'Stupid_Ball'	=>	'Modules/Stupid_Ball/View',
	'Terminal'		=>	'Modules/Terminal/View',
	'Projects'		=>	'Modules/Projects/View',
	'Explorer'		=>	'Modules/Explorer/View',
	'Blog'			=>	'Modules/Blog/View',
	'Assuntos'		=>	'Modules/Assuntos/View',
	'Usuarios'		=>	'Modules/Usuarios/View',
	'Versiculos'	=>	'Modules/Versiculos/View',
	'Parceiros' 	=>	'Modules/Parceiros/View',
	'Calendario' 	=>	'Modules/Calendario/View',
	'CreateCalendar'=>	'Modules/CreateCalendar/View',
	'Album'			=>	'Modules/Album/View',
	'Videos'		=>	'Modules/Videos/View',
);